### ISSUE TITLE
Bot shuts down seconds after joining voice channel

### ISSUE THREAD

**Issue by anabxms** [healzer/DiscordEarsBot#8]
When trying to run, both with pm2 and directly with `node index.js`, the bot crashes

The log with pm2:
```
0|DiscordEarsBot  | 21:04:37: 2021-02-24T00:04:37.361Z :: I'm listening to anabi
0|DiscordEarsBot  | 21:04:37: 2021-02-24T00:04:37.976Z :: I'm listening to lilak
0|DiscordEarsBot  | 21:04:38: 2021-02-24T00:04:38.572Z :: duration: 0.92
0|DiscordEarsBot  | 21:04:38: 2021-02-24T00:04:38.572Z :: TOO SHORT / TOO LONG; SKPPING
0|DiscordEarsBot  | 21:04:39: 2021-02-24T00:04:39.927Z :: duration: 1.7
0|DiscordEarsBot  | 21:04:39: 2021-02-24T00:04:39.960Z :: transcribe_witai
0|DiscordEarsBot  | 21:04:39: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type number
0|DiscordEarsBot  | 21:04:40:     at write_ (_http_outgoing.js:595:11)
0|DiscordEarsBot  | 21:04:40:     at ClientRequest.write (_http_outgoing.js:567:10)
0|DiscordEarsBot  | 21:04:40:     at Request.write (/home/anabia/DiscordEarsBot/node_modules/request/request.js:1494:27)
0|DiscordEarsBot  | 21:04:40:     at Readable.ondata (_stream_readable.js:710:20)
0|DiscordEarsBot  | 21:04:40:     at Readable.emit (events.js:198:13)
0|DiscordEarsBot  | 21:04:40:     at addChunk (_stream_readable.js:288:12)
0|DiscordEarsBot  | 21:04:40:     at readableAddChunk (_stream_readable.js:269:11)
0|DiscordEarsBot  | 21:04:40:     at Readable.push (_stream_readable.js:224:10)
0|DiscordEarsBot  | 21:04:40:     at next (internal/streams/from.js:34:27)
0|DiscordEarsBot  | 21:04:40:     at process._tickCallback (internal/process/next_tick.js:68:7)
```

The one with node:
```
anabia@ubunto:~/DiscordEarsBot$ node index.js --help
2021-02-23T23:49:20.607Z :: Logged in as Ferdinando#8968!
2021-02-23T23:49:48.737Z :: I'm listening to queroumchazin
Falha de segmentação (imagem do núcleo gravada)
```

**Comment by healzer** [comment]
Thanks for reporting this. It seems to be that this happens due to an invalid WITAPIKEY. It should be a string, but says a number is provided. Can you double check your configuration?
